// Self-contained design prototypes. No data leaves this browser.
const params = new URLSearchParams(location.search);
const isSingle = document.body.dataset.single === 'true';
const concept = isSingle ? 1 : ['1','2','3'].includes(params.get('concept')) ? Number(params.get('concept')) : 0;
document.body.classList.add(`concept-${concept}`);
document.querySelector(`[data-concept="${concept}"]`)?.classList.add('selected');
const app = document.getElementById('app');
const modal = document.getElementById('modal');
const mc = document.getElementById('modal-content');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {
  arrow:'M4 12h16m-6-6 6 6-6 6', chevron:'m9 5 7 7-7 7', left:'M20 12H4m6-6-6 6 6 6', search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',
  pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z M15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',
  play:'m9 5 11 7-11 7V5Z', close:'m6 6 12 12M6 18 18 6', menu:'M4 6h16M4 12h16M4 18h16', briefcase:'M3 7h18v14H3V7Zm5 0V3h8v4M3 12h18m-11 0v3h2v-3',
  user:'M20 21v-2a7 7 0 0 0-14 0v2 M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0', camera:'M3 5h12v14H3V5Zm12 5 6-4v12l-6-4', check:'m4 12 5 5L20 6', bookmark:'M6 3h12v18l-6-4-6 4V3Z', clock:'M12 8v5l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0', globe:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0 M2 12h20M12 2c6 6 6 14 0 20-6-6-6-14 0-20'
};
const icon = (name, cls='') => `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name] || paths.arrow}"/></svg>`;
const brand = () => `<a href="#home" class="brand" aria-label="Open Consulting — главная"><span class="brand-symbol"><img src="assets/brand.png" width="1024" height="1024" alt=""></span><span class="brand-word" translate="no"><b>OPEN</b><span>consulting</span></span></a>`;
const jobs = [
 {id:1,title:'Менеджер по продажам',company:'Компания А',symbol:'А',city:'Алматы',country:'Казахстан',salary:'300 000–450 000 ₸',schedule:'Полный день',exp:'1–3 года',cat:'Продажи',desc:'Помогать клиентам выбирать услуги, вести переговоры и сопровождать сделки.',tasks:['Общаться с новыми и действующими клиентами.','Готовить предложения и вести базу клиентов.','Работать с командой над выполнением плана.'],terms:['Фиксированная оплата и премия по результатам.','Обучение продукту и поддержка наставника.','Рабочий график 5/2.']},
 {id:2,title:'Администратор',company:'Компания Б',symbol:'Б',city:'Астана',country:'Казахстан',salary:'от 240 000 ₸',schedule:'Сменный график',exp:'Без опыта',cat:'Сервис',desc:'Встречать гостей, помогать с записью и поддерживать порядок в ежедневных задачах.',tasks:['Встречать посетителей и отвечать на вопросы.','Вести расписание и принимать обращения.','Передавать задачи коллегам.'],terms:['Обучение на месте.','Сменный график по договорённости.','Официальное оформление.']},
 {id:3,title:'Повар',company:'Компания В',symbol:'В',city:'Алматы',country:'Казахстан',salary:'от 280 000 ₸',schedule:'Сменный график',exp:'1–3 года',cat:'Производство',desc:'Готовить блюда по технологическим картам и поддерживать качество кухни.',tasks:['Готовить блюда и заготовки.','Соблюдать санитарные правила.','Поддерживать порядок на рабочем месте.'],terms:['Питание на смене.','Обучение меню и стандартам кухни.','Сменный график.']},
 {id:4,title:'Специалист поддержки',company:'Компания Г',symbol:'Г',city:'Стамбул',country:'Турция',salary:'от 35 000 ₺',schedule:'Полный день',exp:'Без опыта',cat:'Сервис',desc:'Помогать пользователям разбираться с услугами и решать ежедневные вопросы.',tasks:['Отвечать на обращения клиентов.','Уточнять детали и предлагать решения.','Передавать сложные вопросы команде.'],terms:['Обучение перед началом работы.','Нужен русский и разговорный турецкий.','Работа из офиса.']},
 {id:5,title:'Бухгалтер',company:'Компания Д',symbol:'Д',city:'Астана',country:'Казахстан',salary:'350 000–500 000 ₸',schedule:'Полный день',exp:'3–6 лет',cat:'Офис',desc:'Вести учёт первичных документов и готовить отчётность компании.',tasks:['Проверять первичные документы.','Проводить сверки с контрагентами.','Готовить регулярные отчёты.'],terms:['Официальное оформление.','Рабочий график 5/2.','Офис в центре города.']},
 {id:6,title:'Оператор производства',company:'Компания Е',symbol:'Е',city:'Алматы',country:'Казахстан',salary:'от 260 000 ₸',schedule:'Сменный график',exp:'Без опыта',cat:'Производство',desc:'Работать с оборудованием по инструкции и следить за качеством продукции.',tasks:['Подготавливать оборудование к смене.','Следить за рабочими параметрами.','Контролировать качество результата.'],terms:['Обучение безопасной работе.','Рабочая одежда предоставляется.','Сменный график.']}
];
let currentCategory = 'Все', currentQuery = params.get('q') || '', currentCity = params.get('city') || '', noExperience = false;
let selectedJob = null, questionIndex = 0, tutorialIndex = 0, menuOpen = false, toastTimeout;
let recording = false, elapsed = 0, timer = null;
const draft = {name:'',profession:'',experience:'Без опыта',city:'Алматы',about:'',answers:[],visibility:'private',saved:false};
const exampleQuestions = ['Расскажите о вашем опыте работы','Какая задача у вас получилась особенно хорошо?','Какую работу вы ищете сейчас?'];
function questions(){
 const first = draft.experience === 'Без опыта' ? 'Какие навыки вы получили во время учёбы или других занятий?' : 'Расскажите о вашем опыте работы';
 const specific = /продаж|менеджер/i.test(draft.profession) ? 'Как вы поможете клиенту выбрать подходящий вариант?' : /повар/i.test(draft.profession) ? 'Как вы организуете работу, когда заказов много?' : /бухгалтер/i.test(draft.profession) ? 'Как вы проверяете документы перед отчётом?' : 'Расскажите о задаче, с которой вы справились.';
 return [first,specific,'Какую работу вы ищете сейчас?'];
}
function toast(text){const s=document.getElementById('status');s.textContent=text;s.classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>s.classList.remove('visible'),4200);}
function stopTimer(){if(timer)clearInterval(timer);timer=null;recording=false;}
function header(){return `${concept===3 ? `<aside class="workspace-sidebar">${brand()}<nav aria-label="Основная навигация"><a href="#home" class="current">${icon('briefcase')}Найти работу</a><a href="#profile">${icon('user')}Моя анкета</a><a href="#saved">${icon('bookmark')}Сохранённое</a><a href="#how">${icon('camera')}Как это работает</a></nav><div class="sidebar-bottom">Open Consulting<br>Казахстан · Турция<a href="#employers">Работодателям ${icon('arrow')}</a></div></aside>`:''}<header class="header"><div class="container header-inner">${brand()}${concept===3?'<span class="workspace-breadcrumb">Для соискателей / Найти работу</span>':''}<nav aria-label="Основная навигация"><a href="#jobs">Вакансии</a><a href="#how">Как это работает</a><a href="#employers">Работодателям</a></nav><div class="header-tools"><select class="language" aria-label="Язык интерфейса"><option value="ru">RU</option><option value="kz">ҚАЗ</option><option value="tr">TR</option><option value="en">EN</option></select><button class="text-btn login" data-action="login">Войти</button><button class="icon-btn menu-toggle" data-action="menu" aria-label="Открыть меню" aria-expanded="${menuOpen}">${icon(menuOpen?'close':'menu')}</button></div></div></header>${menuOpen?'<nav class="mobile-menu" aria-label="Меню"><a href="#jobs">Вакансии</a><a href="#profile">Создать анкету</a><a href="#how">Как это работает</a><a href="#employers">Работодателям</a><button class="text-btn" data-action="login">Войти</button></nav>':''}`;}
function footer(){return `<footer class="footer"><div class="container"><p>© Open Consulting · Концепция ${concept || '—'}</p><p>Дизайн-прототип. Вакансии и профили демонстрационные.</p></div></footer>`;}
function search(){return `<form class="search" id="search-form" role="search"><div class="field"><label for="query">Должность или компания</label><div class="input-shell">${icon('search')}<input id="query" name="q" value="${esc(currentQuery)}" placeholder="Например, менеджер…" autocomplete="off"><button type="button" class="clear-query ${currentQuery?'visible':''}" aria-label="Очистить запрос" data-action="clear">${icon('close')}</button></div></div><div class="field"><label for="search-city">Город / страна</label><div class="input-shell">${icon('pin')}<select id="search-city" name="city"><option value="">Все города</option>${['Казахстан','Турция','Алматы','Астана','Стамбул'].map(x=>`<option ${currentCity===x?'selected':''}>${x}</option>`).join('')}</select></div></div><button class="btn" type="submit">Найти работу ${icon('arrow')}</button></form>`;}
function popular(){return `<div class="popular"><span>Популярное:</span>${['Продажи','Сервис','Производство','Офис'].map(x=>`<button data-category="${x}">${x}</button>`).join('')}</div>`;}
function heroBottom(){return `<div class="hero-bottom"><a href="#profile" class="text-btn">Создать анкету ${icon('arrow')}</a><p><b>Видео — по желанию.</b> Можно добавить позже.</p></div>`;}
function videoScene(){return `<div class="video-scene"><img src="assets/candidate-demo.png" width="1536" height="1024" loading="lazy" alt="Иллюстрация видеоанкеты: кандидат представляется в светлом рабочем помещении"><span class="video-label">Пример видеоанкеты</span><button class="play" data-action="example" aria-label="Открыть пример видеоответа">${icon('play')}</button><div class="video-question"><div><span>Вопрос ${questionIndex+1} из 3 · пример</span><p class="example-question">${exampleQuestions[questionIndex]}</p></div><div class="question-nav"><button data-action="prev-question" aria-label="Предыдущий вопрос">${icon('left')}</button><button data-action="next-question" aria-label="Следующий вопрос">${icon('arrow')}</button></div></div></div>`;}
function videoSection(){return `<section class="intro-video" id="how"><div class="container video-layout"><div class="video-copy"><div class="eyebrow">Знакомство до собеседования</div><h2>За анкетой —<br>живой человек.</h2><p class="lead">Расскажите о себе своими словами. Вопросы помогут показать ваш опыт, даже если это первая работа.</p><div class="actions"><a class="btn dark" href="#profile">Создать анкету ${icon('arrow')}</a><button class="text-btn" data-action="tutorial">Как заполнить ${icon('play')}</button></div><p class="small muted">Сначала вы посмотрите результат.<br>Публиковать видео необязательно.</p></div>${videoScene()}</div></section>`;}
function humanSection(){return `<section class="intro-video" id="how"><div class="container human-layout"><div class="human-media"><img src="assets/candidate-demo.png" width="1536" height="1024" loading="lazy" alt="Иллюстрация знакомства с кандидатом через видеоанкету"><span class="video-label">Пример профиля</span><button class="play" data-action="example" aria-label="Открыть пример видеоанкеты">${icon('play')}</button><div class="video-question"><div><span>Айгерим · администратор · пример</span><p>«Мне нравится помогать людям»</p></div>${icon('camera')}</div></div><div class="human-copy"><p class="human-kicker">Больше, чем строки в резюме</p><h2>Покажите, как вы думаете и говорите.</h2><p class="lead">Профессия и опыт подскажут вопросы. Вы отвечаете в своём темпе, смотрите результат и решаете, что сохранить.</p><div class="actions"><a href="#profile" class="btn dark">Создать анкету ${icon('arrow')}</a><button class="text-btn" data-action="tutorial">Как это работает</button></div><p class="small muted">Можно начать с обычной анкеты.<br>Видео — дополнительная возможность.</p></div></div></section>`;}
function jobCard(j){if(isSingle)return singleJobCard(j);if(concept===2)return `<button class="job-card" data-job="${j.id}"><span class="job-top"><span class="company-symbol">${j.symbol}</span></span><h3>${j.title}</h3><span class="job-meta">${j.city} · ${j.schedule}</span><span class="salary">${j.salary}</span><span class="job-company">${j.company} · ${j.exp}</span>${icon('arrow','job-arrow')}</button>`;return `<button class="job-card" data-job="${j.id}"><span class="job-top"><span class="company-symbol">${j.symbol}</span>${icon('arrow')}</span><h3>${j.title}</h3><span class="salary">${j.salary}</span><span class="job-meta">${j.city} · ${j.exp}<br>${j.schedule}</span><span class="job-company">${j.company}</span></button>`;}
function filteredJobs(){const q=currentQuery.trim().toLocaleLowerCase('ru');return jobs.filter(j=>(!q||`${j.title} ${j.company} ${j.cat}`.toLocaleLowerCase('ru').includes(q))&&(!currentCity||j.city===currentCity||j.country===currentCity)&&(currentCategory==='Все'||j.cat===currentCategory)&&(!noExperience||j.exp==='Без опыта'));}
function jobsSection(){return `<section class="section" id="jobs"><div class="container"><div class="section-head"><div><h2>${concept===3?'Подходящие вакансии':'Найдите своё место'}</h2><p class="muted small">Демонстрационные вакансии для знакомства с интерфейсом</p></div><span id="result-count" class="muted small" role="status"></span></div><div class="filters" aria-label="Направление работы">${['Все','Продажи','Сервис','Производство','Офис'].map(x=>`<button class="filter ${x===currentCategory?'active':''}" data-filter="${x}" aria-pressed="${x===currentCategory}">${x}</button>`).join('')}<button class="filter ${noExperience?'active':''}" data-action="no-exp" aria-pressed="${noExperience}">Без опыта</button></div><div class="job-list" id="job-list"></div></div></section>`;}
function employerStrip(){return `<section class="employer-strip"><div class="container"><div><h3>Ищете сотрудника?</h3><p class="muted">Познакомьтесь с опытом человека до первой встречи.</p></div><a class="btn secondary" href="#employers">Для работодателей ${icon('arrow')}</a></div></section>`;}
function home(){if(isSingle)return landingHome();if(concept===1)return `<section class="hero"><div class="container"><div class="eyebrow">Работа в Казахстане и Турции</div><div class="hero-top"><h1>Следующая работа.<br>Ваш следующий шаг<span class="red">.</span></h1><div class="hero-aside"><p class="muted small">Опыт есть у каждого.<br>Поможем рассказать о вашем.</p><a href="#how" class="text-btn small">О видеоанкете ${icon('arrow')}</a></div></div><p class="lead">Ищите вакансии или создайте анкету,<br>чтобы работодатели могли найти вас.</p>${search()}${popular()}${heroBottom()}</div></section>${videoSection()}${jobsSection()}${employerStrip()}`;
 if(concept===2)return `<section class="hero"><div class="container"><div class="eyebrow">Open Consulting · поиск работы</div><h1>Хорошая работа начинается<br>с знакомства<span class="red">.</span></h1><p class="lead">Найдите своё место. Расскажите о себе.<br>Познакомьтесь с будущей командой.</p>${search()}${popular()}${heroBottom()}</div></section>${humanSection()}${jobsSection()}${employerStrip()}`;
 return `<section class="hero"><div class="container"><div class="eyebrow">Ваш следующий шаг</div><h1>Работа, которая подходит вам<span class="red">.</span></h1><p class="lead">Выберите направление и город. Или оставьте анкету для работодателей.</p>${search()}<div class="workspace-locations" aria-label="Быстрый выбор места">${['Все города','Алматы','Астана','Стамбул'].map(x=>`<button data-location="${x==='Все города'?'':x}" class="${currentCity===(x==='Все города'?'':x)?'active':''}">${x}</button>`).join('')}</div>${heroBottom()}</div></section><div class="container workspace-main"><div>${jobsSection().replace('<div class="container">','<div>')}</div><section class="workspace-video" id="how">${videoScene()}<h2>Расскажите о себе</h2><p class="lead">Не всё помещается в резюме. Добавьте ответы на вопросы о вашем опыте.</p><a href="#profile" class="btn dark">Создать анкету ${icon('arrow')}</a><button class="text-btn" data-action="tutorial">Как заполнить анкету ${icon('play')}</button><p class="small">Видео — по желанию. Вы сможете посмотреть и перезаписать ответ.</p></section></div>${employerStrip()}`;
}
function fillJobList(){const list=document.getElementById('job-list');if(!list)return;const result=filteredJobs();const jobsCity=document.getElementById("jobs-city");if(jobsCity)jobsCity.value=currentCity;list.innerHTML=result.length?result.map(jobCard).join(''):`<div class="empty"><h3>Пока нет совпадений</h3><p class="muted">Попробуйте другую должность или выберите все города. В прототипе доступно шесть примеров вакансий.</p><button class="btn secondary" data-action="reset-search">Сбросить фильтры</button></div>`;document.getElementById('result-count').textContent=`Найдено: ${result.length}`;document.querySelectorAll('[data-filter]').forEach(b=>{const on=b.dataset.filter===currentCategory;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});document.querySelectorAll('[data-location]').forEach(b=>b.classList.toggle('active',b.dataset.location===currentCity));}
function screenShell(title,content,side='',back='home'){return `<section class="screen"><div class="container"><div class="screen-top"><a class="icon-btn" href="#${back}" aria-label="Назад">${icon('left')}</a><h1>${title}</h1></div><div class="screen-layout"><div>${content}</div><aside class="side-note">${side || '<h3>Ваша анкета — ваш выбор</h3><p>Вопросы зависят от профессии и опыта. Можно оставить обычную анкету и добавить видео позже.</p><p>Это прототип: данные находятся только в памяти страницы и исчезнут после обновления.</p>'}</aside></div></div></section>`;}
function steps(active){return `<ol class="flow-step" aria-label="Этапы создания анкеты">${['О вас','Видео','Просмотр'].map((x,i)=>`<li class="${i===active?'active':''}" ${i===active?'aria-current="step"':''}><b>${i+1}</b>${x}</li>`).join('')}</ol>`;}
function profile(){return screenShell('Создать анкету',`<div class="content-panel">${steps(0)}<div class="form-heading"><h2>С чего начнём?</h2><p class="muted" style="margin-top:12px">Несколько деталей помогут подобрать вопросы о вашем опыте.</p></div><form id="profile-form"><div class="form-grid"><div class="field full"><label for="person-name">Как вас зовут?</label><input id="person-name" name="name" autocomplete="name" placeholder="Имя и фамилия…" value="${esc(draft.name)}" required maxlength="100"></div><div class="field full"><label for="profession">Какая работа вам интересна?</label><input id="profession" name="profession" list="professions" autocomplete="off" placeholder="Например, администратор…" value="${esc(draft.profession)}" required maxlength="120"><datalist id="professions">${['Менеджер по продажам','Администратор','Повар','Бухгалтер','Оператор производства','Специалист поддержки'].map(x=>`<option value="${x}">`).join('')}</datalist></div><div class="field"><label for="experience">Опыт в этой профессии</label><select id="experience" name="experience">${['Без опыта','До 1 года','1–3 года','3–6 лет','Более 6 лет'].map(x=>`<option ${draft.experience===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label for="profile-city">Город поиска</label><select id="profile-city" name="city">${['Алматы','Астана','Стамбул'].map(x=>`<option ${draft.city===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><label for="about">Что хотите добавить? <span class="muted">Необязательно</span></label><textarea id="about" name="about" maxlength="1200" placeholder="Навыки, обучение или предпочтения…">${esc(draft.about)}</textarea></div></div><div class="form-actions"><span class="small muted">Контакты можно будет добавить позже</span><button class="btn" type="submit">Выбрать формат анкеты ${icon('arrow')}</button></div></form></div>`);}
function videoChoice(){return screenShell('Ваша анкета',`<div class="content-panel">${steps(1)}<div class="form-heading"><h2>Как хотите рассказать о себе?</h2><p class="muted" style="margin-top:12px">Оба варианта позволят продолжить поиск работы.</p></div><div class="profile-choice"><div class="choice-card preferred">${icon('camera')}<h3>Добавить видео</h3><p>Ответьте на вопросы. Перед сохранением сможете посмотреть и перезаписать каждый ответ.</p><button class="btn dark" data-action="begin-video">Попробовать сценарий ${icon('arrow')}</button></div><div class="choice-card">${icon('user')}<h3>Продолжить без видео</h3><p>Сохраните основные данные. Видео можно добавить, когда будете готовы.</p><a href="#review" class="btn secondary">Без видео ${icon('arrow')}</a></div></div><div class="notice">В прототипе запись <b>симулируется</b>. Камера и микрофон не включаются.</div><h3 style="font-size:18px;margin-top:28px">Вопросы для вас</h3><ol class="question-list">${questions().map(x=>`<li>${x}</li>`).join('')}</ol><a href="#profile" class="text-btn">${icon('left')} Изменить профессию и опыт</a></div>`,'','profile');}
function recordScreen(){const qs=questions(), answer=draft.answers[questionIndex];return screenShell('Видеоответы',`<div class="content-panel">${steps(1)}<p class="demo-label">Симуляция записи · камера не используется</p><div class="record-frame"><div class="camera-demo"><img src="assets/candidate-demo.png" width="1536" height="1024" alt="Иллюстративный кадр вместо камеры"><span class="record-badge ${recording?'live':''}" id="record-badge">${recording?'Идёт симуляция':'Демонстрационный кадр'}</span></div><div><p class="small muted">Вопрос ${questionIndex+1} из ${qs.length}</p><h2 class="rec-question">${qs[questionIndex]}</h2><p class="small muted">Назовите пример и расскажите, что сделали вы. Можно отвечать своими словами.</p><div class="timer" id="timer">${recording?formatTime(elapsed):answer?'Ответ готов':'Готовы начать?'}</div><div class="rec-actions">${recording?`<button class="btn" data-action="stop-record">Остановить ${icon('check')}</button>`:answer?`<button class="btn dark" data-action="next-answer">${questionIndex===2?'Посмотреть анкету':'Следующий вопрос'} ${icon('arrow')}</button><button class="btn secondary" data-action="start-record">Перезаписать</button>`:`<button class="btn" data-action="start-record">Начать симуляцию ${icon('camera')}</button>`}</div>${answer?'<p class="small muted" style="margin-top:16px">Сохранено состояние ответа. Настоящая видеозапись не создавалась.</p>':''}</div></div><div class="form-actions"><button class="text-btn" data-action="skip-video">Продолжить без видео</button><a href="#video" class="text-btn">${icon('left')} К выбору формата</a></div></div>`,'','video');}
function review(){const count=draft.answers.filter(Boolean).length;return screenShell('Просмотреть анкету',`<div class="content-panel">${steps(2)}<h2>${esc(draft.name || 'Ваша анкета')}</h2><dl class="review-grid" style="margin-top:26px"><dt>Профессия</dt><dd>${esc(draft.profession || 'Не указана')}</dd><dt>Город</dt><dd>${esc(draft.city)}</dd><dt>Опыт</dt><dd>${esc(draft.experience)}</dd><dt>О себе</dt><dd>${esc(draft.about || 'Пока не добавлено')}</dd><dt>Видеоответы</dt><dd>${count?`${count} из 3 · демонстрационные состояния`:'Без видео — можно добавить позже'}</dd></dl><div class="actions" style="margin-top:22px"><a href="#profile" class="text-btn">Изменить данные ${icon('arrow')}</a><a href="#video" class="text-btn">${count?'Изменить видео':'Добавить видео'} ${icon('camera')}</a></div><h3 style="margin-top:32px">Кто сможет видеть анкету?</h3><div class="radio-group"><label class="radio-option"><input type="radio" name="visibility" value="private" ${draft.visibility==='private'?'checked':''}><span><strong>Только по моим откликам</strong>В будущем анкету увидят компании, которым вы откликнетесь.</span></label><label class="radio-option"><input type="radio" name="visibility" value="employers" ${draft.visibility==='employers'?'checked':''}><span><strong>Доступна работодателям</strong>В будущем компании смогут найти вас в базе анкет.</span></label></div><div class="notice">Это демонстрационный черновик. Он <b>не публикуется</b> и не отправляется работодателям.</div><div class="form-actions"><a href="#video" class="text-btn">${icon('left')} Назад</a><button class="btn" data-action="save-profile">Сохранить демо-черновик ${icon('check')}</button></div></div>`,'','video');}
function success(){return `<section class="screen"><div class="container"><div class="success"><div class="success-icon">${icon('check')}</div><h1>Анкета собрана<span class="red">.</span></h1><p class="lead">${selectedJob?'Теперь можно перейти к отклику.':'Теперь можно перейти к вакансиям.'}</p><p class="muted small" style="margin-top:18px">Демо-черновик сохранён до обновления страницы.<br>Данные никуда не отправлены.</p><div class="actions">${selectedJob?`<button class="btn" data-action="demo-apply">Показать результат отклика ${icon('arrow')}</button>`:`<a href="#jobs" class="btn">Найти вакансию ${icon('arrow')}</a>`}<a href="#review" class="btn secondary">Посмотреть анкету</a></div></div></div></section>`;}
function jobDetail(id){const j=jobs.find(x=>x.id===Number(id));if(!j)return screenShell('Вакансия не найдена','<p>Вернитесь к списку и выберите другую вакансию.</p>');selectedJob=j;return `<section class="screen"><div class="container"><a href="#jobs" class="back-link">${icon('left')} К вакансиям</a><p class="demo-label">Демонстрационная вакансия · условия приведены для примера</p><div class="screen-layout"><article class="content-panel job-detail"><h1>${j.title}</h1><p class="salary">${j.salary}</p><p class="muted">${j.city} · ${j.exp} · ${j.schedule}</p><p style="margin-top:28px">${j.desc}</p><h2>Чем предстоит заниматься</h2><ul>${j.tasks.map(x=>`<li>${x}</li>`).join('')}</ul><h2>Условия</h2><ul>${j.terms.map(x=>`<li>${x}</li>`).join('')}</ul><div class="notice">Можно откликнуться с обычной анкетой. Видео поможет дополнить знакомство.</div></article><aside class="content-panel detail-side"><div class="company-symbol">${j.symbol}</div><h3>${j.company}</h3><p>${j.country}, ${j.city}<br>Демонстрационная компания</p><button class="btn" data-action="apply">${draft.saved?'Откликнуться':'Создать анкету и откликнуться'} ${icon('arrow')}</button><button class="btn secondary" data-action="save-job" data-id="${j.id}">${savedJobs.has(j.id)?'Убрать из сохранённого':'Сохранить вакансию'} ${icon('bookmark')}</button><p style="margin-top:18px">Отклик в прототипе не отправляется.</p></aside></div></div></section>`;}
const savedJobs = new Set();
function saved(){return screenShell('Сохранённые вакансии',`<div class="job-list">${savedJobs.size?jobs.filter(j=>savedJobs.has(j.id)).map(jobCard).join(''):'<div class="empty"><h3>Здесь будут интересные вакансии</h3><p class="muted">Откройте вакансию и нажмите «Сохранить вакансию», чтобы вернуться к ней позже в этой сессии.</p><a href="#jobs" class="btn secondary">Посмотреть вакансии</a></div>'}</div>`);}
function employers(){return `<section class="employer-hero"><div class="container"><div class="eyebrow">Для работодателей</div><h1>Познакомьтесь с человеком.<br>Потом назначайте встречу<span class="red">.</span></h1><p class="lead">Вакансия, отклики и видеоответы — в одном месте.<br>Обычная анкета доступна и без видео.</p><div class="actions"><button class="btn" data-action="create-job">Создать демо-вакансию ${icon('arrow')}</button><a href="#home" class="text-btn">Я ищу работу ${icon('arrow')}</a></div><div class="employer-board"><div class="content-panel"><div class="section-head"><h2 style="font-size:28px">Пример откликов</h2><span class="small muted">Администратор</span></div><button class="candidate" data-action="candidate"><img src="assets/candidate-demo.png" width="62" height="72" alt="Иллюстрация кандидата"><span><strong>Айгерим</strong><span class="muted" style="display:block">Алматы · 1 год опыта</span><span class="small red">Есть видеоответы</span></span>${icon('arrow','candidate-arrow')}</button><button class="candidate" data-action="candidate-no-video"><span class="company-symbol">Д</span><span><strong>Данияр</strong><span class="muted" style="display:block">Астана · без опыта</span><span class="small muted">Обычная анкета</span></span>${icon('arrow','candidate-arrow')}</button><p class="tiny muted" style="margin-top:18px">Имена, опыт и отклики демонстрационные.</p></div><div class="content-panel"><h3>От вакансии до встречи</h3><ol class="question-list" style="font-size:16px"><li>Опишите работу и условия.</li><li>Посмотрите анкеты и ответы.</li><li>Пригласите на собеседование.</li></ol><p class="small muted">Видео дополняет опыт и навыки. Решение о встрече принимает работодатель.</p></div></div></div></section>`;}
function index(){return `<main id="main"><section class="index-hero"><div class="container"><div class="eyebrow">Open Consulting · дизайн-исследование</div><h1>Три способа начать<br>знакомство<span class="red">.</span></h1><p class="lead">Разная композиция. Одна идея: найти работу<br>и рассказать о себе до собеседования.</p></div></section><div class="container direction-grid">${[{n:1,name:'Открытая площадка',desc:'Воздух, ясный поиск и спокойное объяснение видеоанкеты.',title:'Следующая работа.<br>Следующий шаг.',cls:''},{n:2,name:'Знакомство',desc:'Выразительная главная и внимание к человеку за анкетой.',title:'Работа начинается<br> с знакомства.',cls:'two'},{n:3,name:'Рабочий кабинет',desc:'Компактная навигация, вакансии и анкета рядом.',title:'Работа, которая<br>подходит вам.',cls:'three'}].map(d=>`<a class="direction-card" href="?concept=${d.n}"><div class="mini-layout ${d.cls}">${d.n===3?'<div class="mini-side"><span class="mini-logo"></span><i></i><i></i><i></i></div><div>':''}<div class="mini-nav"><span class="mini-logo"></span><span class="mini-line"></span><span class="mini-line"></span></div><div class="mini-title">${d.title}</div><div class="mini-search"><span></span><b></b></div><div class="mini-media">${icon('play')}<span class="mini-line" style="width:80px"></span></div>${d.n===3?'</div>':''}</div><div class="direction-body"><span class="small muted">Направление 0${d.n}</span><h2>${d.name}</h2><p>${d.desc}</p><span class="text-btn">Открыть прототип ${icon('arrow')}</span></div></a>`).join('')}</div><div class="container"><p class="index-note">В каждом варианте можно искать вакансии, открыть условия, пройти создание анкеты с видео или без него и посмотреть сценарий работодателя. Все данные демонстрационные. Камера не включается.</p></div></main>`;}
function render(){stopTimer();let hash=location.hash.replace('#','')||'home';if(!concept){app.innerHTML=index();return;}let content;
 if(['home','jobs','how'].includes(hash))content=home();
 else if(hash==='profile')content=profile();else if(hash==='video')content=videoChoice();else if(hash==='record')content=recordScreen();else if(hash==='review')content=review();else if(hash==='success')content=success();else if(hash==='employers')content=employers();else if(hash==='saved')content=saved();else if(hash.startsWith('job-'))content=jobDetail(hash.slice(4));else content=home();
 app.innerHTML=header()+`<main id="main">${content}</main>`+footer();fillJobList();
 if(isSingle){document.querySelector('.hero .search .btn svg')?.remove();if(hash==='jobs')document.body.classList.add('show-results');else document.body.classList.remove('show-results');}
 if(hash==='jobs'||hash==='how')requestAnimationFrame(()=>document.getElementById(hash)?.scrollIntoView());else window.scrollTo({top:0,left:0,behavior:"instant"});
 document.title=isSingle?'Open Consulting — поиск работы':`Open Consulting — ${['','Открытая площадка','Знакомство','Рабочий кабинет'][concept]}`;
}
function navigate(hash){if(location.hash===`#${hash}`)render();else location.hash=hash;}
function showModal(title,body){mc.innerHTML=`<div class="modal-inner"><div class="modal-head"><h2 id="modal-title">${title}</h2><button class="icon-btn" data-action="close-modal" aria-label="Закрыть">${icon('close')}</button></div>${body}</div>`;if(!modal.open)modal.showModal();}
function tutorial(){const stages=[{name:'Выберите профессию',text:'Укажите работу, которая вам интересна, и ваш опыт. Так вопросы будут относиться к вашей ситуации.',demo:'Администратор · Без опыта'},{name:'Добавьте основные данные',text:'Напишите имя, город и то, что хотите рассказать о себе. Это основа анкеты, даже если вы не будете записывать видео.',demo:'Имя · Город · Опыт · Навыки'},{name:'Ответьте на вопросы, если хотите',text:'Прочитайте вопрос, подготовьтесь и начните запись. Посмотрите ответ и перезапишите, если нужно. Можно продолжить без видео.',demo:'Подготовка → Ответ → Просмотр'},{name:'Посмотрите анкету и выберите доступ',text:'Проверьте данные перед сохранением. Вы решаете, кто сможет увидеть вашу анкету.',demo:'Только по откликам / Доступна работодателям'}];const t=stages[tutorialIndex];showModal('Как заполнить анкету',`<p class="muted small">Пошаговая демонстрация. Обучающий ролик будет добавлен позже.</p><div class="tutorial-stage"><div class="tutorial-progress">${stages.map((_,i)=>`<i class="${i<=tutorialIndex?'active':''}"></i>`).join('')}</div><p class="small muted" style="margin-top:20px">Шаг ${tutorialIndex+1} из 4</p><h3>${t.name}</h3><p>${t.text}</p><p class="small muted" style="margin-top:20px">${t.demo}</p></div><div class="actions">${tutorialIndex?'<button class="btn secondary" data-action="tutorial-prev">Назад</button>':''}${tutorialIndex<3?'<button class="btn" data-action="tutorial-next">Следующий шаг</button>':'<button class="btn" data-action="tutorial-finish">Создать анкету</button>'}</div>`);}
function example(){showModal('Пример видеоответа',`<div class="camera-demo" style="aspect-ratio:16/9"><img src="assets/candidate-demo.png" width="1536" height="1024" alt="Иллюстрация демо-кандидата"></div><p class="small muted" style="margin-top:20px">Вопрос: ${exampleQuestions[questionIndex]}</p><h3 style="margin:12px 0">Пример содержания ответа</h3><p>«Я работала администратором: встречала гостей, помогала с записью и отвечала на вопросы. Мне нравится, когда человек уходит с решённой задачей».</p><div class="notice">Текст и изображение иллюстративные. Настоящий ролик пока не снят.</div><div class="actions"><button class="btn dark" data-action="tutorial-finish">Создать свою анкету</button><button class="text-btn" data-action="example-next">Другой вопрос ${icon('arrow')}</button></div>`);}
function candidate(withVideo=true){showModal(withVideo?'Айгерим · администратор':'Данияр · администратор',`<div class="candidate-profile">${withVideo?`<div class="camera-demo"><img src="assets/candidate-demo.png" width="1536" height="1024" alt="Иллюстрация профиля Айгерим"></div>`:'<div class="content-panel"><h3>Без видео</h3><p class="muted" style="margin-top:16px">Кандидат выбрал обычную анкету. Её достаточно, чтобы начать знакомство.</p></div>'}<div><p class="small muted">Демонстрационный кандидат</p><h2>${withVideo?'1 год опыта':'Без опыта'}</h2><p class="lead">${withVideo?'Встреча гостей, работа с расписанием, общение с клиентами.':'Учебные проекты, организация мероприятий, общение с участниками.'}</p><p class="small muted" style="margin-top:16px">${withVideo?'Алматы · русский, казахский':'Астана · русский, казахский'}</p><div class="actions"><button class="btn" data-action="invite">Показать приглашение ${icon('arrow')}</button></div></div></div>`);}
function createJob(){showModal('Создать демо-вакансию',`<form id="job-form"><div class="form-grid"><div class="field full"><label for="job-title">Должность</label><input id="job-title" name="title" required placeholder="Например, администратор…" autocomplete="off" maxlength="120"></div><div class="field"><label for="job-city">Город</label><select id="job-city" name="city"><option>Алматы</option><option>Астана</option><option>Стамбул</option></select></div><div class="field"><label for="job-pay">Зарплата и валюта</label><input id="job-pay" name="pay" placeholder="Например, от 250 000 ₸…" autocomplete="off" maxlength="100"></div><div class="field full"><label for="job-tasks">Основные задачи</label><textarea id="job-tasks" name="tasks" required placeholder="Чем будет заниматься сотрудник…" maxlength="1600"></textarea></div></div><div class="notice">Вакансия не будет опубликована. Это демонстрация формы.</div><button class="btn" type="submit">Посмотреть демо-вакансию ${icon('arrow')}</button></form>`);}
function login(){showModal('Продолжить в Open Consulting',`<p class="muted">Выберите, с какой стороны хотите познакомиться с продуктом.</p><div class="profile-choice"><div class="choice-card"><h3>Ищу работу</h3><p>Анкета, вакансии и знакомство с компаниями.</p><button class="btn dark" data-action="login-candidate">Открыть анкету</button></div><div class="choice-card"><h3>Ищу сотрудника</h3><p>Вакансии и просмотр профилей кандидатов.</p><button class="btn secondary" data-action="login-employer">Открыть демо-кабинет</button></div></div><p class="small muted" style="margin-top:20px">Настоящий вход и регистрация не подключены.</p>`);}
function formatTime(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}
document.addEventListener('click',event=>{
 const job=event.target.closest('[data-job]');if(job){navigate(`job-${job.dataset.job}`);return;}
 const category=event.target.closest('[data-category],[data-filter]');if(category){currentCategory=category.dataset.category||category.dataset.filter;if(isSingle)document.body.classList.add('show-results');fillJobList();document.getElementById('jobs')?.scrollIntoView();return;}
 const loc=event.target.closest('[data-location]');if(loc){currentCity=loc.dataset.location;document.getElementById('search-city').value=currentCity;fillJobList();return;}
 const target=event.target.closest('[data-action]');if(!target)return;
 const action=target.dataset.action;
 if(action==='menu'){menuOpen=!menuOpen;const scroll=window.scrollY;render();window.scrollTo(0,scroll);return;}
 if(action==='clear'){currentQuery='';document.getElementById('query').value='';target.classList.remove('visible');document.getElementById('query').focus();return;}
 if(action==='reset-search'){currentQuery='';currentCity='';currentCategory='Все';noExperience=false;render();return;}
 if(action==='no-exp'){noExperience=!noExperience;target.classList.toggle('active',noExperience);target.setAttribute('aria-pressed',noExperience);fillJobList();return;}
 if(action==='next-question'||action==='prev-question'){questionIndex=(questionIndex+(action==='next-question'?1:2))%3;document.querySelector('.example-question').textContent=exampleQuestions[questionIndex];document.querySelector('.video-question span').textContent=`Вопрос ${questionIndex+1} из 3 · пример`;return;}
 if(action==='tutorial'){tutorialIndex=0;tutorial();return;}
 if(action==='tutorial-next'){tutorialIndex=Math.min(3,tutorialIndex+1);tutorial();return;}
 if(action==='tutorial-prev'){tutorialIndex=Math.max(0,tutorialIndex-1);tutorial();return;}
 if(action==='tutorial-finish'||action==='login-candidate'){modal.close();navigate('profile');return;}
 if(action==='example'){example();return;}
 if(action==='example-next'){questionIndex=(questionIndex+1)%3;example();return;}
 if(action==='close-modal'){modal.close();return;}
 if(action==='login'){login();return;}
 if(action==='login-employer'){modal.close();navigate('employers');return;}
 if(action==='begin-video'){questionIndex=0;navigate('record');return;}
 if(action==='start-record'){stopTimer();elapsed=0;recording=true;app.innerHTML=header()+`<main id="main">${recordScreen()}</main>`+footer();timer=setInterval(()=>{elapsed++;const t=document.getElementById('timer');if(t)t.textContent=formatTime(elapsed);},1000);return;}
 if(action==='stop-record'){stopTimer();draft.answers[questionIndex]={seconds:elapsed,simulated:true};render();return;}
 if(action==='next-answer'){questionIndex++;if(questionIndex>=3){questionIndex=0;navigate('review');}else render();return;}
 if(action==='skip-video'){stopTimer();draft.answers=[];navigate('review');return;}
 if(action==='save-profile'){draft.visibility=document.querySelector('[name="visibility"]:checked')?.value||'private';draft.saved=true;navigate('success');return;}
 if(action==='apply'){if(draft.saved){showModal('Демонстрация отклика',`<p>Анкета «${esc(draft.name)}» выбрана для вакансии «${esc(selectedJob.title)}».</p><div class="notice">Работодатель не получил отклик. Ничего не отправлено.</div><button class="btn" data-action="close-modal">Вернуться к вакансии</button>`);}else{draft.profession=selectedJob.title;draft.city=selectedJob.city;navigate('profile');}return;}
 if(action==='demo-apply'){showModal('Демонстрация отклика',`<h3>${esc(selectedJob?.title||'Вакансия')}</h3><p style="margin-top:16px">В реальном продукте здесь будет подтверждение отправки анкеты компании.</p><div class="notice">Этот отклик никуда не отправлен.</div><button class="btn" data-action="close-modal">Понятно</button>`);return;}
 if(action==='save-job'){const id=Number(target.dataset.id);if(savedJobs.has(id)){savedJobs.delete(id);toast('Вакансия убрана из сохранённого');}else{savedJobs.add(id);toast('Вакансия сохранена в этой сессии');}render();return;}
 if(action==='candidate'){candidate(true);return;}if(action==='candidate-no-video'){candidate(false);return;}
 if(action==='invite'){showModal('Приглашение на встречу',`<p>В реальном продукте вы сможете предложить кандидату время и формат собеседования.</p><div class="notice">Демонстрация: приглашение не отправлено.</div><button class="btn" data-action="close-modal">Вернуться к просмотру</button>`);return;}
 if(action==='create-job'){createJob();return;}
});
document.addEventListener('submit',event=>{
 if(event.target.id==='search-form'){event.preventDefault();const data=new FormData(event.target);currentQuery=String(data.get('q'));currentCity=String(data.get('city'));const u=new URL(location.href);u.searchParams.set('q',currentQuery);u.searchParams.set('city',currentCity);history.replaceState(null,'',u);if(isSingle)document.body.classList.add('show-results');fillJobList();document.getElementById('jobs')?.scrollIntoView();}
 if(event.target.id==='profile-form'){event.preventDefault();const data=new FormData(event.target);for(const name of ['name','profession','experience','city','about'])draft[name]=String(data.get(name)).trim();if(!draft.name||!draft.profession){toast('Укажите имя и профессию');return;}navigate('video');}
 if(event.target.id==='job-form'){event.preventDefault();const data=new FormData(event.target);showModal('Демо-вакансия готова к просмотру',`<h3>${esc(data.get('title'))}</h3><p class="muted" style="margin-top:12px">${esc(data.get('city'))} · ${esc(data.get('pay')||'Зарплата не указана')}</p><p style="white-space:pre-wrap;margin-top:22px">${esc(data.get('tasks'))}</p><div class="notice">Это локальный предпросмотр. Вакансия не опубликована.</div><button class="btn" data-action="close-modal">Закрыть предпросмотр</button>`);}
});
document.addEventListener('input',event=>{if(event.target.id==='query')document.querySelector('.clear-query')?.classList.toggle('visible',!!event.target.value);if(event.target.closest('#profile-form')&&event.target.name in draft)draft[event.target.name]=event.target.value;});
document.addEventListener('change',event=>{if(event.target.classList.contains('language')&&event.target.value!=='ru'){event.target.value='ru';toast('В прототипе доступен русский. Казахский, турецкий и английский запланированы.');}if(event.target.closest('#profile-form')&&event.target.name in draft)draft[event.target.name]=event.target.value;});
window.addEventListener('hashchange',()=>{menuOpen=false;if(modal.open)modal.close();render();});
window.addEventListener('beforeunload',event=>{if(draft.name&&!draft.saved){event.preventDefault();event.returnValue='';}});
render();
