import React,{useState,useRef,useId} from 'react';
import {createRoot} from 'react-dom/client';
import {Theme,Button,IconButton,TextField,Select,SegmentedControl,Dialog,DropdownMenu} from '@radix-ui/themes';
import {ArrowRight,Search,MapPin,Video,ChevronDown,Menu,ArrowUpRight} from 'lucide-react';
import '@radix-ui/themes/styles.css';
import './directions.css';

const assets='/visual-direction/';
const photos={reception:assets+'home/assets/reception.jpg',service:assets+'alternatives/assets/service.jpg',portrait:assets+'alternatives/assets/employee.jpg'};
const studies={
  portal:{name:'Профессии',description:'Профессия → поиск → вакансия. Фото и форма образуют отдельные, связанные области.'},
  people:{name:'Люди и карьера',description:'Рабочая сцена и крупная типографика. Поиск рядом с фотографией, без текста поверх лица.'},
  video:{name:'Видеоанкета',description:'Пример вопросов на первом экране. Главный путь — знакомство с отелем через анкету.'}
};
const samples=[{tab:'Опыт',question:'Расскажите о вашем опыте работы.',hint:'Назовите вашу профессию и задачи, которые вы выполняли.'},{tab:'Профессия',question:'Какую работу вы ищете в отеле?',hint:'Расскажите, какая должность вам интересна и почему.'},{tab:'Языки',question:'Какими языками вы владеете?',hint:'Укажите языки и ситуации, в которых вы ими пользуетесь.'}];
function Logo(){const id=useId();return <svg className="d-logo" viewBox="40 373 895 227" role="img" aria-label="Open Consulting"><defs><clipPath id={id}><rect x="395" y="373" width="600" height="240"/></clipPath></defs><image href={assets+'assets/logo-white.png'} width="1024" height="1024"/><image className="black-wordmark" clipPath={'url(#'+id+')'} href={assets+'assets/logo-white.png'} width="1024" height="1024"/></svg>}

function Header({role,setRole,open,onSearch}){return <header className="d-header"><a href="#main" aria-label="Open Consulting — главная"><Logo/></a><nav aria-label="Основная навигация"><SegmentedControl.Root value={role} onValueChange={setRole} size="2" aria-label="Выберите свою роль"><SegmentedControl.Item value="candidate">Ищу работу</SegmentedControl.Item><SegmentedControl.Item value="hotel">Я работодатель</SegmentedControl.Item></SegmentedControl.Root><Button color="gray" variant="ghost" className="d-nav-job" onClick={onSearch}>{role==='candidate'?'Вакансии':'Разместить вакансию'}</Button></nav><div className="d-header-actions"><DropdownMenu.Root><DropdownMenu.Trigger><Button color="gray" variant="ghost" aria-label="Язык: русский">RU <ChevronDown size={14}/></Button></DropdownMenu.Trigger><DropdownMenu.Content>{['Русский','Қазақша','Türkçe','English'].map(v=><DropdownMenu.Item key={v} onSelect={()=>v!=='Русский'&&open('Язык интерфейса','Переводы будут подготовлены после выбора оформления. Сейчас сравниваем русские первые экраны.')}>{v}</DropdownMenu.Item>)}</DropdownMenu.Content></DropdownMenu.Root><Button color="gray" variant="outline" onClick={()=>open('Войти','Вход по телефону и проверка лица — следующий этап интерфейса. Этот макет не собирает персональные данные.')}>Войти</Button><DropdownMenu.Root><DropdownMenu.Trigger><IconButton color="gray" variant="ghost" className="d-mobile-menu" aria-label="Открыть меню"><Menu size={22}/></IconButton></DropdownMenu.Trigger><DropdownMenu.Content><DropdownMenu.Item onSelect={()=>setRole('candidate')}>Ищу работу</DropdownMenu.Item><DropdownMenu.Item onSelect={()=>setRole('hotel')}>Я работодатель</DropdownMenu.Item><DropdownMenu.Item onSelect={onSearch}>{role==='candidate'?'Вакансии':'Разместить вакансию'}</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Root></div></header>}

function SearchForm({profession,setProfession,city,setCity,role,onSubmit,inputRef,compact=false}){return <form onSubmit={onSubmit} className={'d-search '+(compact?'compact':'')} aria-label={role==='candidate'?'Поиск вакансий':'Новая вакансия'}><label><span>{role==='candidate'?'Кем хотите работать?':'Кого вы ищете?'}</span><TextField.Root ref={inputRef} size="3" value={profession} onChange={e=>setProfession(e.target.value)} placeholder="Например, официант" aria-label="Профессия"><TextField.Slot><Search size={19}/></TextField.Slot></TextField.Root></label><label><span>Город работы</span><Select.Root value={city} onValueChange={setCity}><Select.Trigger size="3" aria-label="Город работы"><span className="d-city"><MapPin size={18}/>{city}</span></Select.Trigger><Select.Content>{['Вся Турция','Анталья','Стамбул','Аланья'].map(v=><Select.Item key={v} value={v}>{v}</Select.Item>)}</Select.Content></Select.Root></label><Button type="submit" size="3">{role==='candidate'?'Найти работу':'Разместить вакансию'}<ArrowRight size={18}/></Button></form>}

function ProfileEntry({role,onProfile,variant='plain'}){return <section className={'d-profile '+variant} aria-label={role==='candidate'?'Анкета с видео':'Кабинет отеля'}><div className="d-profile-icon"><Video size={25}/></div><div><h2>{role==='candidate'?'Расскажите о себе. Отель увидит ваш опыт.':'Познакомьтесь с кандидатами до собеседования.'}</h2><p>{role==='candidate'?'Анкета и короткая видеопрезентация — первый шаг к знакомству.':'Профили, видеопрезентации и приглашения на интервью — в кабинете отеля.'}</p></div><Button color="gray" variant="solid" size="3" onClick={onProfile}>{role==='candidate'?'Создать анкету':'Создать кабинет'}<ArrowRight size={17}/></Button></section>}

function Portal({role,form,onProfile,setProfession,profession}){const choice=profession;const choose=setProfession;return <><section className="portal-layout"><div className="portal-copy"><p className="d-eyebrow">Казахстан <ArrowRight size={15}/> Турция</p><h1>{role==='candidate'?<>Работа в Турции.<br/><em>По вашей профессии.</em></>:<>Ваша команда.<br/><em>Для вашего отеля.</em></>}</h1><p className="d-description">{role==='candidate'?'Выберите направление работы. Найдите вакансию в отеле и познакомьтесь с работодателем.':'Разместите вакансию и знакомьтесь с опытом кандидатов через анкеты и видеопрезентации.'}</p><div className="profession-shortcuts" aria-label="Выберите профессию">{['Официант','Ресепшен','Повар'].map(v=><Button key={v} color="gray" variant={choice===v?'solid':'outline'} size="2" aria-pressed={choice===v} onClick={()=>choose(v)}>{v}<ArrowUpRight size={14}/></Button>)}</div></div><figure className="portal-image"><img src={photos.reception} alt="Сотрудники ресепшен за работой; фотография Rodrigo Salomon"/><figcaption>Ресепшен и работа с гостями</figcaption></figure></section><div className="portal-search-dock">{form}</div><ProfileEntry role={role} onProfile={onProfile}/></>}

function People({role,form,onProfile,onGuide}){return <><section className="people-title"><div><p className="d-eyebrow">Open Consulting · Работа в отелях</p><h1>{role==='candidate'?<>Найдите своё место<br/><em>в отелях Турции.</em></>:<>Люди, которые станут<br/><em>вашей командой.</em></>}</h1></div><div className="people-intro"><p>{role==='candidate'?'Из Казахстана — к новому опыту в гостиничной отрасли Турции. Начните с профессии, которая вам подходит.':'Сервис знакомства отелей Турции с кандидатами из Казахстана. От анкеты и видео — к личному собеседованию.'}</p><Button color="gray" variant="ghost" onClick={onGuide}><Video size={18}/>Как работает видеоанкета<ArrowRight size={16}/></Button></div></section><section className="people-workspace"><figure className="people-photo"><img src={photos.service} alt="Обслуживание гостя в ресторане; фотография Ketut Subiyanto"/><figcaption>Работа с гостями начинается с людей.</figcaption></figure><aside className="people-search"><h2>{role==='candidate'?'Какую работу вы ищете?':'Какой специалист нужен?'}</h2><p>Выберите профессию и город работы.</p>{form}</aside></section><ProfileEntry role={role} onProfile={onProfile} variant="people-profile"/></>}

function QuestionPreview({role}){const [q,setQ]=useState('0');const n=Number(q);return <section className="question-preview" aria-label="Статичный пример вопросов видеоанкеты"><div className="question-head"><Video size={17}/><span>{role==='candidate'?'Подсказки для вашей презентации':'Как отель увидит ответы'}</span><span className="sample-label">Пример</span></div><div className="question-photo"><img src={photos.portrait} alt="Стоковая фотография сотрудницы кафе, Andrea Piacquadio; это не видео и не кандидат платформы"/></div><div className="question-text" aria-live="polite"><h2>{samples[n].question}</h2><p>{samples[n].hint}</p></div><div className="question-controls"><SegmentedControl.Root value={q} onValueChange={setQ} size="2" aria-label="Примеры вопросов">{samples.map((s,i)=><SegmentedControl.Item key={s.tab} value={String(i)}>{s.tab}</SegmentedControl.Item>)}</SegmentedControl.Root><IconButton color="gray" variant="outline" onClick={()=>setQ(String((n+1)%samples.length))} aria-label="Следующий пример вопроса"><ArrowRight size={18}/></IconButton></div><small>Статичный пример с фотографией. Запись видео не подключена.</small></section>}

function VideoDirection({role,form,onProfile}){return <><section className="video-layout"><div className="video-copy"><p className="d-eyebrow">Казахстан <ArrowRight size={15}/> Турция</p><h1>{role==='candidate'?<>Покажите опыт.<br/>Познакомьтесь<br/><em>с отелем.</em></>:<>Увидьте опыт.<br/>Познакомьтесь<br/><em>с кандидатом.</em></>}</h1><p className="d-description">{role==='candidate'?'В анкете — ваши данные. В видео — ваш рассказ о работе. Вопросы на экране помогут начать.':'В профиле — данные кандидата. В видео — его рассказ о работе. Затем можно пригласить на собеседование.'}</p><Button size="4" onClick={onProfile}>{role==='candidate'?'Создать анкету с видео':'Создать кабинет отеля'}<ArrowRight size={19}/></Button><p className="video-detail">{role==='candidate'?'Короткая презентация · 20–40 секунд':'Анкеты и видео · онлайн-собеседование'}</p></div><QuestionPreview role={role}/></section><section className="video-search-dock"><div><h2>{role==='candidate'?'Начните с вакансии':'Начните с вакансии вашего отеля'}</h2><p>{role==='candidate'?'Если уже знаете, какую работу ищете.':'Выберите профессию и место работы.'}</p></div>{form}</section></>}

function App(){
  const query=new URLSearchParams(location.search);const [direction,setDirection]=useState(studies[query.get('direction')]?query.get('direction'):'portal');
  const [role,setRole]=useState('candidate');const [profession,setProfession]=useState('');const [city,setCity]=useState('Вся Турция');const [modal,setModal]=useState(null);const input=useRef(null);
  const open=(title,text)=>setModal({title,text});
  const selectDirection=v=>{setDirection(v);const p=new URLSearchParams(location.search);p.set('direction',v);history.replaceState(null,'',location.pathname+'?'+p)};
  const onProfile=()=>open(role==='candidate'?'Создать анкету':'Создать кабинет отеля',role==='candidate'?'Следующий шаг — регистрация и проверка лица. Затем данные, фотографии, обязательная короткая видеопрезентация и модерация. В этом макете показан только первый экран.':'Следующий шаг — регистрация и проверка компании. После проверки отель размещает вакансии и знакомится с опубликованными анкетами.');
  const onGuide=()=>open('Как работает видеоанкета','Сначала кандидат заполняет сведения и добавляет фотографии. Затем записывает обязательную короткую презентацию. Подсказки помогают рассказать об опыте. После проверки анкета становится доступна подходящим отелям.');
  const submit=e=>{e.preventDefault();open(role==='candidate'?'Поиск вакансий':'Разместить вакансию',role==='candidate'?`Вы выбрали: ${profession.trim()||'любую профессию'} · ${city}. Здесь будет список подходящих вакансий. Реальная база в макет не подключена.`:`Вы указали: ${profession.trim()||'профессию'} · ${city}. Следующий шаг — кабинет проверенного отеля и создание вакансии.`)};
  const form=<SearchForm profession={profession} setProfession={setProfession} city={city} setCity={setCity} role={role} onSubmit={submit} inputRef={input} compact={direction!=='portal'}/>;
  return <Theme accentColor="red" grayColor="slate" radius="medium" className={'directions-app direction-'+direction}>
    <aside className="study-controls" aria-label="Сравнение направлений"><div><strong>Три направления первого экрана</strong><span>{studies[direction].description}</span></div><SegmentedControl.Root value={direction} onValueChange={selectDirection} size="2" aria-label="Визуальное направление">{Object.entries(studies).map(([key,s],i)=><SegmentedControl.Item key={key} value={key}>{i+1}. {s.name}</SegmentedControl.Item>)}</SegmentedControl.Root></aside>
    <div className="direction-page"><Header role={role} setRole={setRole} open={open} onSearch={()=>input.current?.focus()}/><main id="main" key={direction+role} className="direction-main">{direction==='portal'?<Portal role={role} form={form} onProfile={onProfile} setProfession={setProfession} profession={profession}/>:direction==='people'?<People role={role} form={form} onProfile={onProfile} onGuide={onGuide}/>:<VideoDirection role={role} form={form} onProfile={onProfile}/>}</main><footer className="d-footer"><span>Макет первого экрана · вход и вакансии не подключены</span><a href="DIRECTIONS.md">Фото и источники</a></footer></div>
    <Dialog.Root open={!!modal} onOpenChange={v=>!v&&setModal(null)}><Dialog.Content maxWidth="500px"><Dialog.Title>{modal?.title}</Dialog.Title><Dialog.Description size="3">{modal?.text}</Dialog.Description><div className="d-dialog-actions"><Dialog.Close><Button size="3">Понятно</Button></Dialog.Close></div></Dialog.Content></Dialog.Root>
  </Theme>;
}
createRoot(document.getElementById('root')).render(<App/>);

